version: '3.8'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: goapp:${IMAGE_TAG}
    container_name: goapp-container
    ports:
      - "5000:5000"
    restart: unless-stopped
